In [8]:
import pandas as pd

In [9]:
df = pd.read_json('C:\K\social-media-dev-crawler\data\llm_inference\misuse_cases_codes.json')

<>:1: SyntaxWarning: invalid escape sequence '\K'
<>:1: SyntaxWarning: invalid escape sequence '\K'
C:\Users\RESET Lab\AppData\Local\Temp\ipykernel_9568\3563995760.py:1: SyntaxWarning: invalid escape sequence '\K'
  df = pd.read_json('C:\K\social-media-dev-crawler\data\llm_inference\misuse_cases_codes.json')

In [10]:
df.head()

,has_misuse,summary,misuses,post_id
0,True,"The code utilizes a weak, deprecated ChaCha20-...","[{'code_index': '1', 'category': 'WC', 'subtyp...",70094
1,True,The code utilizes a weak cryptographic algorit...,"[{'code_index': '1', 'category': 'WC', 'subtyp...",55014
2,True,The code exhibits several potential weaknesses...,"[{'code_index': '1', 'category': 'WC', 'subtyp...",8687
3,True,The discussion reveals several potential vulne...,"[{'code_index': '1', 'category': 'WC', 'subtyp...",8695
4,True,"The code presents a weak RSA private key, usin...","[{'code_index': '1', 'category': 'WC', 'subtyp...",12378

In [12]:
df[df['post_id'] == 8687]

,has_misuse,summary,misuses,post_id
2,True,The code exhibits several potential weaknesses...,"[{'code_index': '1', 'category': 'WC', 'subtyp...",8687