In [9]:
import pandas as pd

In [10]:
df = pd.read_csv('C:\K\social-media-dev-crawler\data\preprocessed_full_posts.csv')
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\K'
<>:1: SyntaxWarning: invalid escape sequence '\K'
C:\Users\RESET Lab\AppData\Local\Temp\ipykernel_9724\3090596.py:1: SyntaxWarning: invalid escape sequence '\K'
  df = pd.read_csv('C:\K\social-media-dev-crawler\data\preprocessed_full_posts.csv')
C:\Users\RESET Lab\AppData\Local\Temp\ipykernel_9724\3090596.py:1: DtypeWarning: Columns (1,6,7,11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('C:\K\social-media-dev-crawler\data\preprocessed_full_posts.csv')

,site_alias,tags,question_id,accepted_answer_id,answer_count,creation_date,last_activity_date,last_edit_date,owner_id,score,view_count,title,body,site,id,type
0,crypto,tls,55098,NaN,1.0,"2018/01/29, 09:21:12","2018/01/30, 10:27:40","2021/10/07, 07:24:50",55511.0,1,159.0,Tls 1.3 ClientHello legacy_session_id as zero ...,Looking at tls 1.3 draft 23: https://datatrack...,crypto.stackexchange.com.7z,55098,post
1,crypto,authenticated-encryption;poly1305;chacha,66450,67267.0,2.0,"2019/01/13, 06:14:34","2019/02/13, 13:28:19","2021/10/07, 07:34:52",56901.0,3,3234.0,Understanding ChaCha20-Poly1305 AEAD,In the AEAD scheme described in https://www.rf...,crypto.stackexchange.com.7z,66450,post
2,crypto,authenticated-encryption;poly1305;chacha,58036,58038.0,1.0,"2018/04/02, 11:29:54","2018/04/02, 13:38:56","2021/10/07, 07:59:29",57101.0,2,354.0,Should I include the ciphertext length in an A...,I want to construct a time-limited authorizati...,crypto.stackexchange.com.7z,58036,post
3,crypto,hmac;passwords;sha-1;md5,57666,57668.0,1.0,"2018/03/20, 22:32:12","2018/03/21, 00:28:18","2021/10/07, 07:34:52",57101.0,2,61.0,Expanding truly random key into printable pass...,The STUN network protocol defines its client a...,crypto.stackexchange.com.7z,57666,post
4,crypto,tls;rc4,853,NaN,7.0,"2011/09/29, 05:30:51","2014/08/26, 20:58:28","2011/09/29, 08:05:21",38.0,52,33088.0,"Google is using RC4, but isn't RC4 considered ...",Why is Google using RC4 for their HTTPS/SSL?\n...,crypto.stackexchange.com.7z,853,post

In [11]:
full_post = df[df['question_id'] == 66450]
full_post

,site_alias,tags,question_id,accepted_answer_id,answer_count,creation_date,last_activity_date,last_edit_date,owner_id,score,view_count,title,body,site,id,type
1,crypto,authenticated-encryption;poly1305;chacha,66450,67267.0,2.0,"2019/01/13, 06:14:34","2019/02/13, 13:28:19","2021/10/07, 07:34:52",56901.0,3,3234.0,Understanding ChaCha20-Poly1305 AEAD,In the AEAD scheme described in https://www.rf...,crypto.stackexchange.com.7z,66450,post
25469,crypto,NaN,66450,NaN,NaN,2019-02-13T13:28:19.613,NaN,NaN,1172.0,4,NaN,NaN,It is the authentication - which uses Poly-130...,crypto.stackexchange.com.7z,67267,answer
34069,crypto,NaN,66450,NaN,NaN,2019-01-13T12:06:24.473,NaN,NaN,36960.0,1,NaN,NaN,"One advantage it provides, is that you can cal...",crypto.stackexchange.com.7z,66456,answer