In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('C:\K\social-media-dev-crawler\data\preprocessed_full_posts.csv')
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\K'
<>:1: SyntaxWarning: invalid escape sequence '\K'
C:\Users\RESET Lab\AppData\Local\Temp\ipykernel_23352\3090596.py:1: SyntaxWarning: invalid escape sequence '\K'
  df = pd.read_csv('C:\K\social-media-dev-crawler\data\preprocessed_full_posts.csv')

,site_alias,tags,question_id,accepted_answer_id,answer_count,creation_date,last_activity_date,last_edit_date,owner_id,score,view_count,comment_count,title,body,site,id,type
0,crypto.stackexchange.com.7z,cryptanalysis;elliptic-curves;dsa;signature;pu...,71764,NaN,2.0,2019-07-05T17:04:21.550,2019-07-31T10:28:11.473,2019-07-19T20:09:48.763,10.0,15.0,6606.0,6.0,Is it safe to reuse a ECDSA nonce for two sign...,We denote the s value of an ECDSA signature $(...,crypto.stackexchange.com.7z,71764,question
1,crypto.stackexchange.com.7z,encryption;keys;key-derivation;hash,2523,NaN,4.0,2012-05-02T16:42:30.833,2013-01-10T02:25:30.560,2013-01-10T02:25:30.560,2079.0,8.0,5675.0,10.0,Creating an encryption key from several other ...,I want to combine two or more keys to create a...,crypto.stackexchange.com.7z,2523,question
2,crypto.stackexchange.com.7z,secure-storage;keys;public-key,35530,NaN,3.0,2016-05-23T18:38:43.157,2023-07-27T14:12:05.070,2017-05-23T12:41:34.263,NaN,48.0,53375.0,14.0,Where and how to store private keys in web app...,I am working on a web application enabling use...,crypto.stackexchange.com.7z,35530,question
3,crypto.stackexchange.com.7z,block-cipher;algorithm-design;commutative-encr...,6573,NaN,3.0,2013-03-03T21:53:35.237,2015-10-13T12:04:42.333,2017-04-13T12:48:22.310,843.0,21.0,7582.0,6.0,Are there any secure commutative ciphers?,This answer lists two commutative cipher algor...,crypto.stackexchange.com.7z,6573,question
4,crypto.stackexchange.com.7z,cryptanalysis;file-encryption,72384,NaN,7.0,2019-08-05T11:28:18.697,2019-08-08T01:08:37.403,2019-08-07T18:27:14.967,8532.0,18.0,22652.0,11.0,How to check a file was encrypted (really & co...,I would like to audit how an implementation of...,crypto.stackexchange.com.7z,72384,question

In [5]:
df[df['question_id'] == 71764]

,site_alias,tags,question_id,accepted_answer_id,answer_count,creation_date,last_activity_date,last_edit_date,owner_id,score,view_count,comment_count,title,body,site,id,type
0,crypto.stackexchange.com.7z,cryptanalysis;elliptic-curves;dsa;signature;pu...,71764,NaN,2.0,2019-07-05T17:04:21.550,2019-07-31T10:28:11.473,2019-07-19T20:09:48.763,10.0,15.0,6606.0,6.0,Is it safe to reuse a ECDSA nonce for two sign...,We denote the s value of an ECDSA signature $(...,crypto.stackexchange.com.7z,71764,question
272,crypto,NaN,71764,NaN,0.0,2019-07-23T03:57:09.507,2019-07-31T10:28:11.473,2021-10-07T07:59:29.080,17884.0,6.0,0.0,2.0,NaN,Suppose you have two message signature pairs a...,crypto.stackexchange.com.7z,72112,answer
623,crypto,NaN,71764,NaN,0.0,2019-07-20T01:52:50.273,2019-07-23T15:42:16.513,2019-07-23T15:42:16.513,70619.0,0.0,0.0,9.0,NaN,NO! because if you use the same K(random numbe...,crypto.stackexchange.com.7z,72066,answer
1472,crypto,NaN,71764,NaN,0.0,2019-07-05T19:50:51.913,NaN,NaN,NaN,0.0,0.0,0.0,NaN,What happens when you add another signature $s...,crypto.stackexchange.com.7z,158544,comment
1474,crypto,NaN,71764,NaN,0.0,2019-07-08T15:21:51.130,NaN,NaN,10.0,0.0,0.0,0.0,NaN,I believe this is the same security as the cas...,crypto.stackexchange.com.7z,158680,comment
1475,crypto,NaN,71764,NaN,0.0,2019-07-19T19:42:38.863,NaN,NaN,17884.0,0.0,0.0,0.0,NaN,Your derivation of $k$ when $x_1 = x_2$ is wro...,crypto.stackexchange.com.7z,159275,comment
1476,crypto,NaN,71764,NaN,0.0,2019-07-19T20:10:55.627,NaN,NaN,10.0,0.0,0.0,0.0,NaN,"Thanks, I got the numerator and denominator re...",crypto.stackexchange.com.7z,159278,comment
1478,crypto,NaN,71764,NaN,0.0,2019-07-31T19:07:59.337,NaN,NaN,13903.0,0.0,0.0,0.0,NaN,"If this happens, then the second signer (owner...",crypto.stackexchange.com.7z,159905,comment
1479,crypto,NaN,71764,NaN,0.0,2019-08-01T20:51:47.937,NaN,NaN,10.0,0.0,0.0,0.0,NaN,"Yes, both signer are allowed to know both $k, ...",crypto.stackexchange.com.7z,159941,comment